# Generated by Django 4.1.5 on 2023-01-26 21:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='project',
        ),
        migrations.AlterField(
            model_name='engagement',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Numero do engagement'),
        ),
        migrations.CreateModel(
            name='ProjectEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_user', models.UUIDField()),
                ('update_user', models.UUIDField(null=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engagement.engagement')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
    ]
