# Generated by Django 4.1.5 on 2023-01-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_user', '0001_initial'),
        ('engagement', '0002_remove_engagement_project_alter_engagement_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectengagement',
            name='users',
            field=models.ManyToManyField(blank=True, to='project_user.projectuser'),
        ),
    ]
