# Generated by Django 4.1.5 on 2023-01-31 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0003_projectengagement_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectengagement',
            name='engagement',
        ),
        migrations.RemoveField(
            model_name='projectengagement',
            name='project',
        ),
        migrations.AddField(
            model_name='engagement',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='engagement.projectengagement'),
        ),
    ]
