# Generated by Django 4.1.5 on 2023-01-26 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='descripiton',
            new_name='description',
        ),
    ]
