"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import datetime
import re
import os
import sys
import urllib3
import warnings

from pathlib import Path
from dotenv import load_dotenv
from kombu import Exchange, Queue
from core.drfmsal import IdentityWebPython
from decouple import config

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
urllib3.disable_warnings()

warnings.filterwarnings("ignore", message="You have a duplicated operationId")
warnings.filterwarnings('ignore', message='DateTimeField LoginRecord.login_time received a naive datetime')
# warning rest_framework.W001:  You have specified a default PAGE_SIZE pagination rest_framework setting,
# without specifying also a DEFAULT_PAGINATION_CLASS. PAGINATION_CLASS is added dynamically according to whether the
# class is pagination or not
SILENCED_SYSTEM_CHECKS = ['rest_framework.W001']

if '--env' in sys.argv:
    # get the index of the --env argument
    env_index = sys.argv.index('--env') + 1

    # load the .env file based on the specified environment
    env = sys.argv[env_index]
    env_file = f".env.{env}"

    if env not in ['dev', 'prod', 'hml', 'azure']:
        raise ValueError('Incorrect option to use the --env argument. The options are: dev, prod, hml, azure')

    if not os.path.exists(env_file):
        raise ValueError(f'Configuration file not found to: {env_file}')

    del sys.argv[env_index]
    del sys.argv[env_index - 1]
    load_dotenv(env_file)

else:
    load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', cast=str)

PASSWD_DEV = config('PASSWD_DEV', cast=str, default='fake_passwd')
DTT_EMAIL = config('DTT_EMAIL', cast=str, default='')

DEBUG = config('DEBUG', cast=bool, default=False)
ENABLE_SSO = config('ENABLE_SSO', cast=bool, default=True)
ENABLE_TOKEN = config('ENABLE_TOKEN', cast=bool, default=False)
ENABLE_DRF = config('ENABLE_DRF', cast=bool, default=True)
DATABASE_POSTGRES = config('DATABASE_POSTGRES', cast=bool, default=False)
ENVIRONMENT = config('ENVIRONMENT', cast=str, default='prod').lower()
ENABLE_LOGGER = config('ENABLE_LOGGER', cast=bool, default=False)
ENABLE_CACHE = config('ENABLE_CACHE', cast=bool, default=False)
DEBUG_TOOLBAR = config('DEBUG_TOOLBAR', cast=bool, default=False)
TEST_PW = config('TEST_PW', cast=str, default="User@123")
LOGGING_FILE_LEVEL = config('LOGGING_FILE_LEVEL', default='DEBUG', cast=str)

LOGGING_FILE_HANDLERS = config('LOGGING_FILE_HANDLERS', default='console,critical,info,error,warning', cast=str).split(
    ',')

if ENVIRONMENT not in ['prod', 'hml', 'dev']:
    raise ValueError('Invalid ENVIRONMENT. Options is (prod, hml or dev)')

IS_PROD = ENVIRONMENT == 'prod'
IS_HML = ENVIRONMENT == 'hml'
IS_DEV = ENVIRONMENT == 'dev'

# Application definition

INSTALLED_APPS = [
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_extensions',  # TEMP
    'import_export',
    'rest_framework',
    "drf_standardized_errors",  # Alter output erros in REST API
    'drf_api_logger',  # Custom logger info
    'drf_yasg',  # Swagger schema
    # 'vinaigrette',
    'modeltranslation',  # Custom field translation
    'django_apscheduler',  # Eventos crontab
    'django_celery_results',  # View results Tasks in admin
    'encrypted_fields',
    'django_filters',

    # Base
    'base',
    'base.claim',
    'base.coins',

    # Dashboard
    'dashboard',

    # Creditors
    'creditors',
    'creditors.classes',
    'creditors.notice',

    # Recovering
    'recovering',
    'recovering.archive',
    'recovering.archive_recovering',

    # Project
    'projects',
    'projects.judge',
    'projects.lawyer',
    'projects.region',  # Comarca
    'projects.court',  # Vara
    'projects.engagement',
    'projects.project_user',

    # Core
    'core.dttuser.apps.DTTUserConfig',
    'core.abstract',
    'core.permission',
    'core.entity',

    # Security
    'security',
    'security.formula',  # Salvar formulas utilizadas no momento do cálculo

    # Calculation
    'calculation',
    'calculation.criterion',
    'calculation.comment',  # Comentários ao longo de cada passo do calculo
    'calculation.verdict',
    'calculation.funds',  # Verbas
    'calculation.premise',  # Premissas(Observações) do cálculo
    'calculation.statement',  # Extrato contábil
    'calculation.statement_pf',  # Extrato contábil PF
    'calculation.statement_pj',  # Extrato contábil PJ
    'calculation.comparative',  # Comparativo
    'calculation.funds.document',  # Verbas documento
    'calculation.funds.deduction',  # Verbas Dedução de pagamentos
    'calculation.funds.integrations',  # Verbas Integratórias
    'calculation.funds.irrf',  # Verbas IRRF
    'calculation.funds.danos',  # Verbas danos
    'calculation.sheets_template',  # Templates Planilhas Excel

    # Rate - Índice
    'rates',

    # Big Numbers - KPIS e Gráficos
    'big_number',

    # Files
    'file',

    # Scheduler
    'apps.schedule',
    'apps.scrapper',

]

FIELD_HASH_KEY = config('FIELD_HASH_KEY', default='cef9dc82b9360609c35ee23ab333c00996275635a106e959c8211dd59fcf990b',
                        cast=str)

FIELD_ENCRYPTION_KEYS = FIELD_HASH_KEY.split(',')

SITE_ID = 1

AUTH_USER_MODEL = 'dttuser.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'crum.CurrentRequestUserMiddleware',  # Get current request in Models
    'drf_api_logger.middleware.api_logger_middleware.APILoggerMiddleware',
    'dashboard.middleware.LoginMiddleware',  # Save the first occurrence of user login on the day
]

ROOT_URLCONF = 'config.urls'

DRF_API_LOGGER_DATABASE = True

template = 'templates'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'juca/static/src/vue/dist/', os.path.join(BASE_DIR, template)
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'custom_filters': 'base.templatetags.custom_filters',

            }
        },
    },
]

DEFAULT_AUTHENTICATION_CLASSES = [
    "rest_framework.authentication.SessionAuthentication",
]
# Logging file
# https://docs.djangoproject.com/en/3.2/topics/logging/
if IS_PROD or ENABLE_LOGGER:
    path_file_logs = os.path.join(BASE_DIR, 'log')
    os.makedirs(path_file_logs, exist_ok=True)
    file_log = os.path.join(path_file_logs, str(datetime.datetime.now().date()) + '_{}.log')
    log_format = "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s"

    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "simple": {
                "format": "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
            },
            "verbose": {
                "format": "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s"
            }
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "level": "DEBUG",
                "formatter": "simple",
                "stream": "ext://sys.stdout",
            },
            "debug": {
                "class": 'apps.handler.LevelSpecificFileHandler',
                "level": "DEBUG",
                "custom_level": "DEBUG",
                "formatter": "verbose",
                "filename": file_log.format("debug"),
            },
            "critical": {
                'class': 'apps.handler.LevelSpecificFileHandler',
                "level": "CRITICAL",
                "custom_level": "CRITICAL",
                "formatter": "verbose",
                "filename": file_log.format("critical"),
            },
            "error": {
                'class': 'apps.handler.LevelSpecificFileHandler',
                "level": "ERROR",
                "custom_level": "ERROR",
                "formatter": "verbose",
                "filename": file_log.format("error"),
            },
            "info": {
                'class': 'apps.handler.LevelSpecificFileHandler',
                "level": "INFO",
                "custom_level": "INFO",
                "formatter": "verbose",
                "filename": file_log.format("info"),
            },
            "warning": {
                'class': 'apps.handler.LevelSpecificFileHandler',
                "level": "WARNING",
                "custom_level": "WARNING",
                "formatter": "verbose",
                "filename": file_log.format("warning"),
            },
        },
        "loggers": {
            "root": {
                "handlers": LOGGING_FILE_HANDLERS,
                "level": LOGGING_FILE_LEVEL,
                "propagate": True,
            },
            "": {
                "handlers": LOGGING_FILE_HANDLERS,
                "level": LOGGING_FILE_LEVEL,
                "propagate": False,
            },
            "django": {
                "handlers": LOGGING_FILE_HANDLERS,
                "level": LOGGING_FILE_LEVEL,
                "propagate": False,
            },
            'django.request': {  # capturar logs relacionados a requisições HTTP
                'handlers': LOGGING_FILE_HANDLERS,
                "level": LOGGING_FILE_LEVEL,
                'propagate': False,
            },
            'django.utils.autoreload': {  # capturar logs relacionados a requisições HTTP
                'handlers': LOGGING_FILE_HANDLERS,
                "level": "ERROR",
                'propagate': False,
            },
            "werkzeug": {  # capturar logs do runser_plus,
                "handlers": LOGGING_FILE_HANDLERS,
                "level": LOGGING_FILE_LEVEL,
                "propagate": False,
            },
        }
    }

if IS_PROD:
    ALLOWED_HOSTS = [
        'fadigitallab.deloitte.com.br',
    ]

    CSRF_TRUSTED_ORIGINS = [
        'https://fadigitallab.deloitte.com.br/juca',
    ]

elif IS_HML:
    ALLOWED_HOSTS = [
        'uat.fadigitallab.deloitte.com.br',
    ]

    CSRF_TRUSTED_ORIGINS = [
        'https://uat.fadigitallab.deloitte.com.br/juca',
    ]

else:
    ALLOWED_HOSTS = ['localhost', 'https://127.0.0.1', 'https://127.0.0.2', 'juca', 'brdcvmdev07']

    CSRF_TRUSTED_ORIGINS = [
        'https://uat.fadigitallab.deloitte.com.br/juca',
        'https://fadigitallab.deloitte.com.br/juca',
        'https://dev.fadigitallab.deloitte.com.br/juca',
        'https://www.brdcvmdev07/juca',
        'https://www.brfojwanderley/juca',
        'https://www.brsphearndt/juca',
        'https://www.brspwaoliveira/juca',
    ]

# Enable Login SSO
if ENABLE_SSO:
    MIDDLEWARE.append('core.drfmsal.middleware.MsalMiddleware')
    # DRFMSAL AUTHENTICATION
    DRFMSAL_CONFIG = {
        'id_web_configs': 'MS_ID_WEB_CONFIGS',
        'graph_url': 'https://graph.microsoft.com/v1.0',
        'client': {
            'client_id': str(os.getenv('MSAL_CLIENT_ID')),
            'client_credential': str(os.getenv('MSAL_CLIENT_SECRET')),
            'authority': f'https://login.microsoftonline.com/{str(os.getenv("MSAL_DTT_TENANT"))}/'
        },
        'auth_request': {
            'scopes': ['User.Read'],
            'response_type': 'code'
        },
    }

    GRAPH_IMG_WIDTH = config('GRAPH_IMG_WIDTH', cast=str, default='240x240')

    DRFMSAL_IDENTITY_WEB = IdentityWebPython(resolution=GRAPH_IMG_WIDTH)

else:
    DRFMSAL_IDENTITY_WEB = {}
    DRFMSAL_CONFIG = {}

# Enable Cors to dev mode or local mode
if ENABLE_TOKEN:
    INSTALLED_APPS.append('rest_framework.authtoken')
    DEFAULT_AUTHENTICATION_CLASSES.append('rest_framework.authentication.TokenAuthentication')

    MIDDLEWARE.append("corsheaders.middleware.CorsMiddleware")
    INSTALLED_APPS.append('corsheaders')
    CORS_ALLOWED_ORIGINS = [
        'https://*',
        'http://*',
    ]
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = True

    CSRF_TRUSTED_ORIGINS = [
        'http://127.0.0.1:8000',
        'https://brfojwanderley:5173',
        'https://brspwaoliveira:8080/juca',
        'https://brdcvmdev07/juca',
        'https://brsphearndt:8080/juca',
        'https://uat.fadigitallab.deloitte.com.br/juca',
        'https://fadigitallab.deloitte.com.br/juca',
        'https://dev.fadigitallab.deloitte.com.br/juca',
        'https://10.127.145.231:8000/juca'
    ]

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# str(os.getenv('SECRET_KEY'))
# if 'test' in sys.argv:
#    ENABLE_SSO=False
if IS_DEV or 'test' in sys.argv:
    my_string = sys.argv[0].replace('\\', '').replace('/', '')

    if my_string.endswith('main.py'):
        if DATABASE_POSTGRES is False:
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.sqlite3',
                    'NAME': ':memory:',
                    'MIRROR': 'default',
                    'OPTIONS': {
                        'timeout': 40,  # Define o timeout em segundos (exemplo: 40 segundos)
                    },
                },
            }

            # cria uma cópia do banco de dados atual para testes do locust
            import shutil
            import tempfile
            import os

            tmpdir = os.path.join(tempfile.gettempdir(), 'juca')
            tmp_db = os.path.join(tmpdir, 'tmp.sqlite3')
            if os.path.exists(tmpdir) is False:
                os.mkdir(tmpdir)
            if os.path.exists(tmp_db) is False:
                shutil.copy2(BASE_DIR / 'db.sqlite3', tmp_db)
            DATABASES['default']['NAME'] = tmp_db
        else:
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.postgresql',
                    'NAME': str(os.getenv('DB_NAME')),
                    'USER': str(os.getenv('DB_USER')),
                    'PASSWORD': str(os.getenv('DB_PASS')),
                    'HOST': str(os.getenv('DB_HOST')),
                    'PORT': str(os.getenv('DB_PORT')),
                }
            }
    else:
        if DATABASE_POSTGRES:
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.postgresql',
                    'NAME': str(os.getenv('DB_NAME')),
                    'USER': str(os.getenv('DB_USER')),
                    'PASSWORD': str(os.getenv('DB_PASS')),
                    'HOST': str(os.getenv('DB_HOST')),
                    'PORT': str(os.getenv('DB_PORT')),
                    'TEST': {
                        'MIRROR': 'default',
                    },
                }
            }
        else:
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.sqlite3',
                    'NAME': BASE_DIR / 'db.sqlite3',
                    'TEST': {
                        'MIRROR': 'default',
                    },
                    'OPTIONS': {
                        'timeout': 60,  # Define o timeout em segundos (exemplo: 40 segundos)
                    },
                }
            }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', cast=str),
            'USER': config('DB_USER', cast=str),
            'PASSWORD': config('DB_PASS', cast=str),
            'HOST': config('DB_HOST', cast=str),
            'PORT': config('DB_PORT', cast=str),
        }
    }

# Caches
# https://docs.djangoproject.com/en/4.2/topics/cache/
if not DEBUG:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.db.DatabaseCache",
            "LOCATION": "django_juca_cache_table",
        },

    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }
databases = DATABASES

# Add these two lines.
# import dj_database_url
# DATABASES['default'] = dj_database_url.config(default='sqlite://db/sqlite3.db')
# PW validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-pw-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en'
# LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / 'locale'
]

gettext = lambda s: s
LANGUAGES = (
    ('pt-br', gettext('Português')),
    ('en', gettext('English')),
)

MODELTRANSLATION_DEFAULT_LANGUAGE = 'pt-br'

MODELTRANSLATION_LANGUAGES = ('en', 'pt-br')

TEMPLATE_CONTEXT_PROCESSORS = (
    'django.template.context_processors.i18n',
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
# if IS_DEV:
#     import mimetypes
#
#     mimetypes.add_type("application/javascript", ".js", True)
#     mimetypes.add_type("text/css", ".css", True)

STATIC_URL = '/juca/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'var', 'static_root')

# Setting media info for images
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'juca', 'static'),
]
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {

    # Setting Global permissions, to require authentication
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTO_SCHEMA_CLASS': 'core.abstract.views.CustomSwaggerAutoSchema',

    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": DEFAULT_AUTHENTICATION_CLASSES,
    'TEST_REQUEST_RENDERER_CLASSES': [
        'rest_framework.renderers.MultiPartRenderer',
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.TemplateHTMLRenderer'
    ],
    "DEFAULT_RENDERER_CLASSES": (
        "core.drfmsal.renderer.APIRendererInterceptor",
        "rest_framework.renderers.BrowsableAPIRenderer"
    ),
    'PAGE_SIZE': 10,
}

if ENABLE_DRF:
    REST_FRAMEWORK['EXCEPTION_HANDLER'] = "drf_standardized_errors.handler.exception_handler"

DRF_STANDARDIZED_ERRORS = {"ENABLE_IN_DEBUG_FOR_UNHANDLED_EXCEPTIONS": True}
# Setting auth user
AUTH_USER_MODEL = 'dttuser.User'
BASE_URL = 'juca/api/v1/'  # Current version
BASE_URL_NEXT = 'juca/api/v2/'  # Next version
BASE_URL_AUTH = 'juca/api/'

# Documentation login Urls
if IS_DEV:
    LOGIN_URL = "/juca/login/"
    LOGOUT_REDIRECT_URL = f"/{BASE_URL}docs/swagger/"
    LOGIN_REDIRECT_URL = f"/{BASE_URL}docs/swagger/"
    LOGOUT_URL = "/juca/logout/"
    # Start config debug toolbar
    INTERNAL_IPS = [
        # ...
        "127.0.0.1",
        "127.0.0.3",
        # ...
    ]

else:
    LOGIN_URL = "/juca/login/"
    LOGOUT_REDIRECT_URL = f"/juca/"
    LOGIN_REDIRECT_URL = f"/juca/"
    LOGOUT_URL = "/juca/logout/"

if DEBUG_TOOLBAR:
    INSTALLED_APPS.append('debug_toolbar')
    MIDDLEWARE.append('debug_toolbar.middleware.DebugToolbarMiddleware')

    INTERNAL_IPS = [
        # ...
        "127.0.0.1",
        "127.0.0.3",
        # ...
    ]

SWAGGER_URL = f'/{BASE_URL}docs/redoc/'
RATE_FILE_TYPES = ['pdf', 'vnd.ms-excel', 'xlsx', 'xls']

TEMPLATE_FILE_TYPES = ['vnd.ms-excel', 'xlsx', 'xls', 'xlsm']

GROUP_NAME_EXECUTOR = 'Executor'
GROUP_NAME_APPROVER = 'Aprovador'
GROUP_NAME_SPECIAL_APPROVE = 'Aprovador Especial'
GROUP_NAME_REVIEWER = 'Revisor'
GROUP_NAME_PARTNER = 'Sócio'
GROUP_NAME_FINANCIAL_MANAGER = 'Gestor Financeiro'
GROUP_NAME_CALCULATION_MANAGER = 'Gestor Cálculo'
GROUP_NAME_LEGAL_MANAGER = 'Gestor Jurídico'
GROUP_NAME_SECURITY = 'Security'

ROLES = [GROUP_NAME_EXECUTOR, GROUP_NAME_APPROVER, GROUP_NAME_SPECIAL_APPROVE, GROUP_NAME_REVIEWER, GROUP_NAME_SECURITY]

INDEX_VARIATION_END = os.getenv('INDEX_VARIATION_END', '2017-09-01')
INDEX_VARIATION_END = datetime.datetime.strptime(INDEX_VARIATION_END, '%Y-%m-%d').date()

TOKEN_TEST = os.getenv('TOKEN_TEST')  # Token para a execução de teste em ambientes controlados
INDEX_VARIATION_RJ = os.getenv('INDEX_VARIATION_RJ', '2022-06-01')
INDEX_VARIATION_RJ = datetime.datetime.strptime(INDEX_VARIATION_RJ, '%Y-%m-%d').date()

# Key to encrypt or decrypt text
FERNET_KEY = os.getenv('FERNET_KEY').encode()

# tipo de conteúdo aceito pelo worker, para ser usado no res de tarefas.
accept_content = ['application/json']
# formato de serialização a ser usado para as tarefas.
task_serializer = 'json'
# formato de serialização a ser usado para os resultados das tarefas.
result_serializer = 'json'
# número de processos em que o worker será executado simultaneamente.
worker_concurrency = 2
# número máximo de conexões com o Redis permitido (quando usado como backend).
redis_max_connections = 18
# número máximo de conexões do pool do broker permitido.
broker_pool_limit = 18
# tempo (em segundos) que um worker espera antes de considerar uma tarefa perdida e tentar executá-la novamente.
worker_lost_wait = 20
# número máximo de tarefas que um processo do worker pode executar antes de ser reiniciado.
worker_max_tasks_per_child = 6
# define a URL do Redis usada como back do Celery
celery_url = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379')
# URL do broker usada pelo Celery.
broker_url = celery_url
# define se o broker deve tentar reconectar em caso de falha na inicialização.
broker_connection_retry_on_startup = True
# backend usado para armazenar os resultados das tarefas (neste caso, banco de dados do Django).
result_backend = 'django-db'
# result_backend = celery_url
# fila padrão para as tarefas.
task_default_queue = 'default'
# habilita recursos adicionais do resultado das tarefas (como hora de execução, tempo de início/fim etc.).
result_extended = True
# backend de cache usado pelo Celery.
cache_backend = 'redis'
# troca padrão usada pelo Celery (uma Exchange chamada 'media', do tipo 'direto').
default_exchange = Exchange('media', type='direct')
# start no traceback de resultado da task no TaskResult
task_track_started = True
result_persistent = True

# tupla com todas as filas usadas pelo Celery. Neste caso, apenas uma fila chamada 'media_queue' é definida, com uma
# chave de roteamento ('routing_key') chamada 'video'.
task_queues = (Queue('media_queue', exchange=default_exchange, routing_key='video'),)

# CACHES["redis"] = {
#     "BACKEND": "django_redis.cache.RedisCache",
#     "LOCATION": celery_url,
#     "OPTIONS": {
#         "CLIENT_CLASS": "django_redis.client.DefaultClient"
#     }
# }
# os.environ.setdefault('FORKED_BY_MULTIPROCESSING', '1')
# broker_url = celery_url
# result_backend = 'rci://'
# result_backend = celery_url
# CELERY_RESULT_BACKEND_DB  = celery_url
SALT_KEY = '0123456789abcdefghijklmnopqrstuvwxyz'
