"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from core.drfmsal import IdentityWebPython

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = str(os.getenv('SECRET_KEY'))

# # SECURITY WARNING: don't run with debug turned on in production!
# if (str(os.getenv('ENV')) == 'branch') or (str(os.getenv('ENV')) == 'dev') or (str(os.getenv('ENV')) == 'hml'):
#     DEBUG = str(os.getenv('debug')) == "True"
# else:
#     DEBUG = str(os.getenv('ENV')) == "True"

DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1', 
    'localhost', 
    'brdcvmdev01' # TEMP
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_extensions', #TEMP
    'import_export',

    'rest_framework',

    'projetos',
    'core.dttuser.apps.DTTUserConfig'

]

AUTH_USER_MODEL = 'dttuser.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'core.drfmsal.middleware.MsalMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'static/src/vue/dist/'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# DRFMSAL AUTHENTICATION
DRFMSAL_CONFIG = {
    'id_web_configs': 'MS_ID_WEB_CONFIGS',
    'graph_url': 'https://graph.microsoft.com/v1.0',
    'client': {
        'client_id': str(os.getenv('MSAL_CLIENT_ID')),
        'client_credential': str(os.getenv('MSAL_CLIENT_SECRET')),
        'authority': f'https://login.microsoftonline.com/{str(os.getenv("MSAL_DTT_TENANT"))}/'
    },
    'auth_request': {
        'scopes': ['User.Read'],
        'response_type': 'code'
    },
}
DRFMSAL_IDENTITY_WEB = IdentityWebPython()
# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

#str(os.getenv('SECRET_KEY'))

if str(os.getenv('ENV')) == 'branch':
    DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            
            'NAME': str(os.getenv('DB_NAME')),
            
            'USER': str(os.getenv('DB_USER')),

            'PASSWORD': str(os.getenv('DB_PASS')),

            'HOST': str(os.getenv('DB_HOST')),

            'PORT': str(os.getenv('DB_PORT')),
        }
    }



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'var/static_root/'
STATICFILES_DIRS = ['static']
if DEBUG:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static')
    ]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'var/static_root/')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Setting media info for images
MEDIA_URL = "/media/"
MEDIA_ROOT = "uploads"



REST_FRAMEWORK = {

    # Setting Global permissions, to require authentication
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],

    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_RENDERER_CLASSES": (
        "core.drfmsal.renderer.APIRendererInterceptor",
        "rest_framework.renderers.BrowsableAPIRenderer"
    )
}

#setting auth user
AUTH_USER_MODEL = 'dttuser.User'

if DEBUG:
    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)
