# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
trigger:
- dev
pool: 
  name: TR
  demands:
  - Agent.Name -equals TRDEV
strategy:
  matrix:
    DJUD:
      PYTHON_VERSION: '3.10.10'
  maxParallel: 3
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10.10'
    allowUnstable: true
    architecture: 'x64'
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '8.x'
- task: DownloadSecureFile@1
  name: Env
  inputs:
    secureFile: '.env'
- script: |
    echo Installing $(EnvPrd.secureFilePath) to the path backend...
    copy $(Env.secureFilePath) $(Build.SourcesDirectory)/backend 
- task: DownloadSecureFile@2
  name: Env-frontend
  inputs:
    secureFile: '.env-frontend'
- script: |
    echo Installing $(EnvPrd.secureFilePath) to the path backend...
    copy $(Env-frontend.secureFilePath) $(Build.SourcesDirectory)/frontend 
- task: PythonScript@0
  displayName: 'Export project path'
  inputs:
    scriptSource: 'inline'
    script: |
      """Search all subdirectories for `manage.py`."""
      from glob import iglob
      from os import path
      # Python >= 3.10.10
      manage_py = next(iglob(path.join('**', 'manage.py'), recursive=True), None)
      if not manage_py:
          raise SystemExit('Could not find a Django project')
      project_location = path.dirname(path.abspath(manage_py))
      print('Found Django project in', project_location)
      print('##vso[task.setvariable variable=projectRoot]{}'.format(project_location))
- script: |
    npm install --force
    npm run build:prod
  workingDirectory: $(Build.SourcesDirectory)/frontend
  displayName: 'Install node prerequisites'
- script: |
    mkdir ./log
    pip install virtualenv
    virtualenv venv
    ./venv/Scripts/activate
    python -m pip install --upgrade pip setuptools wheel
    pip install -r requirements.txt >> arq1.txt
    pip install unittest-xml-reporting
    pip install fastcgi
    python manage.py collectstatic
  workingDirectory: $(Build.SourcesDirectory)/backend
  displayName: 'Install and preparing python prerequisites'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/backend'
    Contents: '**'
    TargetFolder: 'D:\DJUD\'
    OverWrite: true
    flattenFolders: true
