# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
trigger:
- dev
pool: 
  name: TR
  demands:
  - Agent.Name -equals TRDEV
variables:
  system.debug: 'true'
strategy:
  matrix:
    DJUD:
      PYTHON_VERSION: '3.10.10'
  maxParallel: 3
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    allowUnstable: true
    architecture: 'x64'
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '18.x'
    checkLatest: true
- task: DownloadSecureFile@1
  name: Env
  inputs:
    secureFile: '.env'
- task: DownloadSecureFile@1
  name: EnvFrontEnd
  inputs:
    secureFile: '.env-frontend'
- script: |
    echo Installing $(Env.secureFilePath) to the path backend...
    copy $(Env.secureFilePath) $(Build.SourcesDirectory)\backend\.env
  failOnStderr: true
- script: |
    echo Installing $(EnvFrontEnd.secureFilePath) to the path frontend...
    copy $(EnvFrontEnd.secureFilePath) $(Build.SourcesDirectory)\frontend\.env
  failOnStderr: true
- task: PythonScript@0
  displayName: 'Export project path'
  inputs:
    scriptSource: 'inline'
    script: |
      """Search all subdirectories for `manage.py`."""
      from glob import iglob
      from os import path
      # Python >= 3.10.10
      manage_py = next(iglob(path.join('**', 'manage.py'), recursive=True), None)
      if not manage_py:
          raise SystemExit('Could not find a Django project')
      project_location = path.dirname(path.abspath(manage_py))
      print('Found Django project in', project_location)
      print('##vso[task.setvariable variable=projectRoot]{}'.format(project_location))
- script: |
    npm install
  failOnStderr: true
  workingDirectory: $(Build.SourcesDirectory)/frontend
  displayName: 'Install node prerequisites'
- script: |
    npm run build:prod
  failOnStderr: false
  workingDirectory: $(Build.SourcesDirectory)/frontend
  displayName: 'Install node prerequisites'
- script: |
    md .\log
  failOnStderr: true
  workingDirectory: $(Build.SourcesDirectory)/backend
  displayName: 'Install and preparing python prerequisites'
- script: |
    pip install virtualenv
  failOnStderr: true
  workingDirectory: $(Build.SourcesDirectory)/backend
  displayName: 'Install and preparing python prerequisites'
- script: |
    virtualenv venv
  failOnStderr: true
  workingDirectory: $(Build.SourcesDirectory)/backend
  displayName: 'Install and preparing python prerequisites'
- script: |
    .\venv\Scripts\activate
  failOnStderr: true
  workingDirectory: $(Build.SourcesDirectory)/backend
  displayName: 'Install and preparing python prerequisites'
- script: |
    pip install --upgrade pip setuptools wheel
  failOnStderr: true
  workingDirectory: $(Build.SourcesDirectory)/backend
  displayName: 'Install and preparing python prerequisites'
- script: |
    pip install -r requirements.txt
  failOnStderr: false
  workingDirectory: $(Build.SourcesDirectory)/backend
  displayName: 'Install and preparing python prerequisites'
- script: |
    pip install unittest-xml-reporting
  failOnStderr: true
  workingDirectory: $(Build.SourcesDirectory)/backend
  displayName: 'Install and preparing python prerequisites'
- script: |
    python -m pip install fastcgi
  failOnStderr: true
  workingDirectory: $(Build.SourcesDirectory)/backend
  displayName: 'Install and preparing python prerequisites'
- script: |
    python manage.py collectstatic --no-input
  failOnStderr: true
  workingDirectory: $(Build.SourcesDirectory)/backend
  displayName: 'Install and preparing python prerequisites'
- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/backend/venv'
    Contents: '**'
    RemoveSourceFolder: true
- script: |
    python manage.py makemigrations
  failOnStderr: true
  workingDirectory: $(Build.SourcesDirectory)/backend
  displayName: 'Install and preparing python prerequisites'
- script: |
    del venv\.*
  failOnStderr: false
  workingDirectory: $(Build.SourcesDirectory)/backend
  displayName: 'Install and preparing python prerequisites'
- script: |
    python manage.py migrate --fake
  failOnStderr: true
  workingDirectory: $(Build.SourcesDirectory)/backend
  displayName: 'Install and preparing python prerequisites'
- script: |
    rd venv
  failOnStderr: false
  workingDirectory: $(Build.SourcesDirectory)/backend
  displayName: 'Install and preparing python prerequisites'
- script: |
    del .env
  failOnStderr: true
  workingDirectory: $(Build.SourcesDirectory)/backend
  displayName: 'Install and preparing python prerequisites'
- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/backend/__pycache__'
    Contents: '**'
    RemoveSourceFolder: true
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/backend'
    Contents: '**'
    TargetFolder: 'D:\JUCA'
    OverWrite: true
    flattenFolders: false