# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    DJUD:
      PYTHON_VERSION: '3.9'
  maxParallel: 3

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    architecture: 'x64'
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '8.x'
- task: PythonScript@0
  displayName: 'Export project path'
  inputs:
    scriptSource: 'inline'
    script: |
      """Search all subdirectories for `manage.py`."""
      from glob import iglob
      from os import path
      # Python >= 3.9
      manage_py = next(iglob(path.join('**', 'manage.py'), recursive=True), None)
      if not manage_py:
          raise SystemExit('Could not find a Django project')
      project_location = path.dirname(path.abspath(manage_py))
      print('Found Django project in', project_location)
      print('##vso[task.setvariable variable=projectRoot]{}'.format(project_location))

- script: |
    npm install
    npm run build
  workingDirectory: $(Build.SourcesDirectory)/frontend
  displayName: 'Install node prerequisites'

- script: |
    python -m pip install --upgrade pip setuptools wheel
    pip install virtualenv
    virtualenv venv
    python -m pip install --upgrade pip setuptools wheel
    pip install -r requirements.txt
    pip install unittest-xml-reporting
    pip install fastcgi
    python manage.py makemigrations
    python manage.py migrate
    python manage.py collectstatic
  workingDirectory: $(Build.SourcesDirectory)/backend
  variables:
    ENV='dev'
    debug:'True'
    SECRET_KEY_MONGO:''
    SECRET_KEY:'ey+_ix$avrz=zpjr=zj6dhayyec=cd^&5%nm5d*k$s$qf!#q9q'
    DB_PASS_GERAL:''
    DB_USER:'a-hearndt'
    DB_PASS:'7GizEiIBF41p'
    DB_PORT:'5433'
    DB_HOST:'BRDCVMDB05'
    DB_NAME:'PROJETO_DJUD_DEV'
    MSAL_CLIENT_ID:'a55d74a8-7a9b-41d4-a520-c6b238533430'
    MSAL_CLIENT_SECRET:'PaW8Q~.LIyWtlKCl69h1gJnD1JQyQv1brPaTSaL2'
    MSAL_DTT_TENANT:'36da45f1-dd2c-4d1f-af13-5abe46b99921'
  displayName: 'Install and preparing python prerequisites'

