# Generated by Django 4.1.5 on 2023-01-26 19:08

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_user', models.UUIDField()),
                ('update_user', models.UUIDField(null=True)),
                ('eng_number', models.PositiveIntegerField(blank=True, null=True)),
                ('client', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('project_start', models.DateField(blank=True, null=True)),
                ('project_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Em andamento', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
    ]
