# Generated by Django 4.1.5 on 2023-01-26 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_rename_descripiton_judge_description'),
        ('project', '0002_remove_project_image_alter_project_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.AddField(
            model_name='project',
            name='judge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='judge.judge'),
        ),
    ]
