# Generated by Django 4.1.5 on 2023-01-26 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layer', '0002_rename_descripiton_layer_description'),
        ('region', '0002_rename_descripiton_region_description'),
        ('project', '0004_remove_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='eng_number',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='', max_length=150, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='project',
            name='layer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='layer.layer'),
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='region.region'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='E', max_length=1),
        ),
    ]
