# Generated by Django 4.1.5 on 2023-01-31 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0004_remove_projectengagement_engagement_and_more'),
        ('project', '0005_remove_project_eng_number_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='engagement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='engagement.projectengagement'),
        ),
    ]
