# Generated by Django 4.1.5 on 2023-01-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='update_user',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
