# Generated by Django 4.1.5 on 2023-01-31 15:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_user', models.UUIDField()),
                ('update_user', models.UUIDField(null=True)),
                ('name', models.CharField(max_length=150)),
                ('legal_number', models.CharField(max_length=14)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
    ]
