# Generated by Django 4.0.6 on 2022-07-27 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_number', models.PositiveIntegerField(blank=True, null=True)),
                ('client', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('project_start', models.DateField(blank=True, null=True)),
                ('project_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Em andamento', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ManyToManyField(related_name='projetos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
