// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Btn: typeof import('./components/common/Btn.vue')['default']
    FooterBar: typeof import('./components/common/FooterBar.vue')['default']
    GraphGauge: typeof import('./components/common/GraphGauge.vue')['default']
    GraphLine: typeof import('./components/common/GraphLine.vue')['default']
    Hint: typeof import('./components/common/Hint.vue')['default']
    Img: typeof import('./components/common/Img.vue')['default']
    InputDate: typeof import('./components/inputs/InputDate.vue')['default']
    InputSelect: typeof import('./components/inputs/InputSelect.vue')['default']
    InputTags: typeof import('./components/inputs/InputTags.vue')['default']
    InputText: typeof import('./components/inputs/InputText.vue')['default']
    InputUser: typeof import('./components/inputs/InputUser.vue')['default']
    Modal: typeof import('./components/common/Modal.vue')['default']
    NavBar: typeof import('./components/common/NavBar.vue')['default']
    NewProject: typeof import('./components/project/NewProject.vue')['default']
    NotificationArea: typeof import('./components/common/NotificationArea.vue')['default']
    ProgressList: typeof import('./components/common/ProgressList.vue')['default']
    QItem: typeof import('quasar')['QItem']
    QSelect: typeof import('quasar')['QSelect']
    QTd: typeof import('quasar')['QTd']
    ReloadBtn: typeof import('./components/common/ReloadBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFilter: typeof import('./components/common/SearchFilter.vue')['default']
    Spinner: typeof import('./components/common/Spinner.vue')['default']
    TimeoutBar: typeof import('./components/common/TimeoutBar.vue')['default']
    UserCell: typeof import('./components/project/UserCell.vue')['default']
  }
}
