// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Accordion: typeof import('./components/common/Accordion.vue')['default']
    Breadcrumbs: typeof import('./components/common/Breadcrumbs.vue')['default']
    Btn: typeof import('./components/common/Btn.vue')['default']
    FooterBar: typeof import('./components/layout/FooterBar.vue')['default']
    GraphCard: typeof import('./components/graph/GraphCard.vue')['default']
    GraphGauge: typeof import('./components/graph/GraphGauge.vue')['default']
    GraphLine: typeof import('./components/graph/GraphLine.vue')['default']
    Header: typeof import('./components/common/Header.vue')['default']
    Hint: typeof import('./components/common/Hint.vue')['default']
    Img: typeof import('./components/common/Img.vue')['default']
    InputDate: typeof import('./components/inputs/InputDate.vue')['default']
    InputLegal: typeof import('./components/inputs/InputLegal.vue')['default']
    InputSelect: typeof import('./components/inputs/InputSelect.vue')['default']
    InputTags: typeof import('./components/inputs/InputTags.vue')['default']
    InputText: typeof import('./components/inputs/InputText.vue')['default']
    InputUser: typeof import('./components/inputs/InputUser.vue')['default']
    InputUsers: typeof import('./components/inputs/InputUsers.vue')['default']
    Modal: typeof import('./components/common/Modal.vue')['default']
    NavBar: typeof import('./components/layout/NavBar.vue')['default']
    NewProject: typeof import('./components/project/NewProject.vue')['default']
    NotificationArea: typeof import('./components/common/NotificationArea.vue')['default']
    Page: typeof import('./components/common/Page.vue')['default']
    ProgressList: typeof import('./components/graph/ProgressList.vue')['default']
    ProjectDetailCell: typeof import('./components/project/ProjectDetailCell.vue')['default']
    QBtn: typeof import('quasar')['QBtn']
    QCard: typeof import('quasar')['QCard']
    QSeparator: typeof import('quasar')['QSeparator']
    QTab: typeof import('quasar')['QTab']
    QTabs: typeof import('quasar')['QTabs']
    ReloadBtn: typeof import('./components/common/ReloadBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFilter: typeof import('./components/inputs/SearchFilter.vue')['default']
    Spinner: typeof import('./components/common/Spinner.vue')['default']
    StatusTag: typeof import('./components/common/StatusTag.vue')['default']
    TimeoutBar: typeof import('./components/common/TimeoutBar.vue')['default']
    UserCell: typeof import('./components/common/UserCell.vue')['default']
    UserPicture: typeof import('./components/common/UserPicture.vue')['default']
    UserTag: typeof import('./components/common/UserTag.vue')['default']
  }
}
