// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Accordion: typeof import('./components/common/Accordion.vue')['default']
    Btn: typeof import('./components/common/Btn.vue')['default']
    copy: typeof import('./components/common/GraphLine copy.vue')['default']
    FooterBar: typeof import('./components/common/FooterBar.vue')['default']
    Graph: typeof import('./components/common/Graph.vue')['default']
    GraphCard: typeof import('./components/common/GraphCard.vue')['default']
    GraphGauge: typeof import('./components/common/GraphGauge.vue')['default']
    GraphLine: typeof import('./components/common/GraphLine.vue')['default']
    GraphNumber: typeof import('./components/common/GraphNumber.vue')['default']
    GraphResume: typeof import('./components/common/GraphResume.vue')['default']
    Hint: typeof import('./components/common/Hint.vue')['default']
    Img: typeof import('./components/common/Img.vue')['default']
    InputDate: typeof import('./components/inputs/InputDate.vue')['default']
    InputLegal: typeof import('./components/inputs/InputLegal.vue')['default']
    InputSelect: typeof import('./components/inputs/InputSelect.vue')['default']
    InputTags: typeof import('./components/inputs/InputTags.vue')['default']
    InputTags2: typeof import('./components/inputs/InputTags2.vue')['default']
    InputText: typeof import('./components/inputs/InputText.vue')['default']
    InputUser: typeof import('./components/inputs/InputUser.vue')['default']
    InputUsers: typeof import('./components/inputs/InputUsers.vue')['default']
    Modal: typeof import('./components/common/Modal.vue')['default']
    NavBar: typeof import('./components/common/NavBar.vue')['default']
    NewProject: typeof import('./components/project/NewProject.vue')['default']
    NotificationArea: typeof import('./components/common/NotificationArea.vue')['default']
    ProgressList: typeof import('./components/common/ProgressList.vue')['default']
    ProjectDetailCell: typeof import('./components/project/ProjectDetailCell.vue')['default']
    QField: typeof import('quasar')['QField']
    ReloadBtn: typeof import('./components/common/ReloadBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFilter: typeof import('./components/common/SearchFilter.vue')['default']
    Spinner: typeof import('./components/common/Spinner.vue')['default']
    TimeoutBar: typeof import('./components/common/TimeoutBar.vue')['default']
    UserCell: typeof import('./components/common/UserCell.vue')['default']
    UserPicture: typeof import('./components/common/UserPicture.vue')['default']
    UserTag: typeof import('./components/common/UserTag.vue')['default']
  }
}
