# Generated by Django 4.1.5 on 2023-01-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0002_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
